# Setup
title:               VR20 Glasgow
tagline:             "Vegan Runners UK's Scottish 20<sup>th</sup> anniversary celebration"
description:         "A guide to all of the great fun, running, and people at
                      Vegan Runners UK's 20th anniversary celebration in Glasgow,
                      Scotland October 4th-6th."
url:                 https://alanocallaghan.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Vegan Runners
  url:               https://www.veganrunners.org.uk/
  email:             alan.ocallaghan@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: /:basename/ # make URL of pages in the folder _pages as on the root.
include:
  - _pages
