# Setup
title:               VR20 Glasgow
tagline:             "Vegan Runners UK's Scottish 20th anniversary celebration"
description:         "A guide to all of the great fun, running, and people at
                      Vegan Runners UK's 20th anniversary celebration in Glasgow,
                      Scotland October 4th-6th."
url:                 https://alanocallaghan.github.io/vr20glasgow
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              VR
  url:               https://www.veganrunners.org.uk/
  email:             lorem@ipsum.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

