# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'Site description'
url:                 http://alanocallaghan.github.io/vr2020glasgow
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              VR
  url:               https://www.veganrunners.org.uk/
  email:             lorem@ipsum.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
